# Generated by Django 5.2.1 on 2025-07-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_expired_at_payment_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expired_at',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_expired',
        ),
    ]
