# Generated by Django 5.2.1 on 2025-07-03 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_expired_at_payment_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
