# Generated by Django 5.2.1 on 2026-05-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.IntegerField(),
        ),
    ]
