# Generated by Django 5.2.1 on 2026-05-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_plans_slug_alter_plans_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Member Monthly', 'Member Monthly'), ('Non Member Hourly', 'Non Member Hourly')], default='Member Monthly', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_member_only',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
