# Generated by Django 5.2.1 on 2026-05-06 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_expires_at_payment_amount_and_more'),
        ('subscription', '0002_remove_subscription_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='plan',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscription.subscription'),
        ),
        migrations.AddField(
            model_name='plans',
            name='installment_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_paid_in_installment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='is_member_only',
            field=models.BooleanField(default=True),
        ),
    ]
