# Generated by Django 5.2.1 on 2026-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_plan_payment_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
