# Generated by Django 5.2.1 on 2026-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='payment',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Partial Active', 'Partial Active'), ('Active', 'Active'), ('Pending', 'Pending'), ('Expired', 'Expired'), ('Expired Partial', 'Expired Partial'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
    ]
