# Generated by Django 5.2.1 on 2026-07-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subscription_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
