# /etc/nginx/sites-available/api.test.hub.borderlessunn.xyz
# Staging. TLS lines are added/managed by certbot --nginx.

server {
    listen 80;
    server_name api.test.hub.borderlessunn.xyz;

    client_max_body_size 10M;

    location /static/ {
        alias /var/www/borderless-hub-app-backend-test/staticfiles/;
        access_log off;
        expires 30d;
    }

    location / {
        proxy_pass http://127.0.0.1:8002;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}
