# Generated by Django 5.2.1 on 2025-06-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customadmin_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadmin',
            name='no_use',
        ),
    ]
