# Generated by Django 5.2.1 on 2025-06-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customadmin_no_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
