# Generated by Django 5.2.1 on 2025-06-07 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True)),
                ('department', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_checkin', models.DateField(blank=True, null=True)),
                ('tech_stack', models.CharField(max_length=200)),
                ('is_member', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='customadmin',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='customadmin',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
