# Generated by Django 5.2.1 on 2025-06-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customadmin_groups_customadmin_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadmin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customadmin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customadmin',
            name='user_permissions',
        ),
    ]
