# Generated by Django 5.2.1 on 2025-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
