# Generated by Django 5.2.1 on 2025-07-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_last_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_checkin',
        ),
    ]
