# Generated by Django 5.2.1 on 2026-05-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='whatsapp_number',
            new_name='phone_number',
        ),
    ]
