# Generated by Django 5.2.1 on 2026-07-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_whatsapp_number_customuser_phone_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super', 'Super Admin'), ('staff', 'Staff Admin')], help_text='Only set for admin accounts (is_superuser=True). Null for members/non-members.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_member', True)), fields=('phone_number',), name='unique_member_phone_number'),
        ),
    ]
