# Generated by Django 5.2.1 on 2026-05-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='subscription_id',
            new_name='subscription',
        ),
    ]
