# Generated by Django 5.2.1 on 2026-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_closure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubclosuredate',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hubclosuredate',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
