# Generated by Django 5.2.1 on 2025-07-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
